# Data analysis with pandas 2

In [1]:
import pandas as pd

## Load data from CSV file into Pandas dataframe

In [2]:
covid_data_df = pd.read_csv('covid-countries-data.csv')

In [3]:
covid_data_df

           location  total_cases  total_deaths  total_tests
0       Afghanistan      38243.0        1409.0          NaN
1           Albania       9728.0         296.0          NaN
2           Algeria      45158.0        1525.0          NaN
3           Andorra       1199.0          53.0          NaN
4            Angola       2729.0         109.0          NaN
..              ...          ...           ...          ...
207  Western Sahara        766.0           1.0          NaN
208           World   26059065.0      863535.0          NaN
209           Yemen       1976.0         571.0          NaN
210          Zambia      12415.0         292.0          NaN
211        Zimbabwe       6638.0         206.0      97272.0

[212 rows x 4 columns]

## Information of dataframe

In [4]:
covid_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   location      212 non-null    object
 1   total_cases   211 non-null    float64
 2   total_deaths  211 non-null    float64
 3   total_tests   90 non-null     float64
dtypes: float64(3), object(1)
memory usage: 6.8+ KB

## Count the number of countries for which the total_tests data is missing

In [5]:
covid_data_df[covid_data_df.total_tests.isna()]

           location  total_cases  total_deaths  total_tests
0       Afghanistan      38243.0        1409.0          NaN
1           Albania       9728.0         296.0          NaN
2           Algeria      45158.0        1525.0          NaN
3           Andorra       1199.0          53.0          NaN
4            Angola       2729.0         109.0          NaN
..              ...          ...           ...          ...
205       Venezuela      48883.0         398.0          NaN
207  Western Sahara        766.0           1.0          NaN
208           World   26059065.0      863535.0          NaN
209           Yemen       1976.0         571.0          NaN
210          Zambia      12415.0         292.0          NaN

[122 rows x 4 columns]

In [6]:
total_tests_missing = covid_data_df[covid_data_df.total_tests.isna()].shape[0]

In [7]:
print("The data for total tests is missing for {} countries.".format(int(total_tests_missing)))

The data for total tests is missing for 122 countries.

## Merge countries_df with covid_data_df on the location column

In [8]:
countries_df = pd.read_csv('countries.csv')

In [9]:
combined_df = countries_df.merge(covid_data_df, on='location')

In [10]:
combined_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_cases,total_deaths,total_tests
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,38243.0,1409.0,NaN
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,9728.0,296.0,NaN
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,45158.0,1525.0,NaN
3,Andorra,Europe,77265.0,83.73,NaN,NaN,1199.0,53.0,NaN
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,2729.0,109.0,NaN
...,...,...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884,1046.0,35.0,261004.0
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN,766.0,1.0,NaN
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,1976.0,571.0,NaN
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,12415.0,292.0,NaN
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,6638.0,206.0,97272.0

## Add columns tests_per_million, cases_per_million and deaths_per_million into combined_df ?

In [14]:
combined_df['tests_per_million'] = combined_df['total_tests'] * 1e6 / combined_df['population']

In [15]:
combined_df.sample(5)

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_cases,total_deaths,total_tests,tests_per_million
27,Brazil,South America,212559409.0,75.88,2.2,14103.452,3997865.0,123780.0,4797948.0,22572.268255
14,Bahrain,Asia,1701583.0,77.29,2.0,43290.705,52440.0,190.0,1118837.0,657527.137965
163,Sao Tome and Principe,Africa,219161.0,70.39,2.9,3052.714,896.0,15.0,NaN,NaN
8,Armenia,Asia,2963234.0,75.09,4.2,8787.580,44075.0,884.0,NaN,NaN
16,Barbados,North America,287371.0,79.19,5.8,16978.068,176.0,7.0,NaN,NaN

In [16]:
combined_df['cases_per_million'] = combined_df['total_cases'] * 1e6 / combined_df['population']

In [17]:
combined_df['deaths_per_million'] = combined_df['total_deaths'] * 1e6 / combined_df['population']

In [18]:
combined_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
0,Afghanistan,Asia,38928341.0,64.83,0.50,1803.987,38243.0,1409.0,NaN,NaN,982.394806,36.194710
1,Albania,Europe,2877800.0,78.57,2.89,11803.431,9728.0,296.0,NaN,NaN,3380.359997,102.856349
2,Algeria,Africa,43851043.0,76.88,1.90,13913.839,45158.0,1525.0,NaN,NaN,1029.804468,34.776824
3,Andorra,Europe,77265.0,83.73,NaN,NaN,1199.0,53.0,NaN,NaN,15518.022390,685.950948
4,Angola,Africa,32866268.0,61.15,NaN,5819.495,2729.0,109.0,NaN,NaN,83.033462,3.316470
...,...,...,...,...,...,...,...,...,...,...,...,...
205,Vietnam,Asia,97338583.0,75.40,2.60,6171.884,1046.0,35.0,261004.0,2681.403324,10.745996,0.359570
206,Western Sahara,Africa,597330.0,70.26,NaN,NaN,766.0,1.0,NaN,NaN,1282.373228,1.674116
207,Yemen,Asia,29825968.0,66.12,0.70,1479.147,1976.0,571.0,NaN,NaN,66.250993,19.144391
208,Zambia,Africa,18383956.0,63.89,2.00,3689.251,12415.0,292.0,NaN,NaN,675.317108,15.883415
209,Zimbabwe,Africa,14862927.0,61.49,1.70,1899.775,6638.0,206.0,97272.0,6544.605918,446.614587,13.859989

## Create a dataframe with 10 countires that have highest number of tests per million people ?

In [19]:
highest_tests_df = combined_df.sort_values('tests_per_million', ascending=False).head(10)

In [20]:
highest_tests_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
197,United Arab Emirates,Asia,9890400.0,77.97,1.200,67293.483,71540.0,387.0,7177430.0,725696.635121,7233.276713,39.128852
14,Bahrain,Asia,1701583.0,77.29,2.000,43290.705,52440.0,190.0,1118837.0,657527.137965,30818.361490,111.660730
115,Luxembourg,Europe,625976.0,82.25,4.510,94277.965,7928.0,124.0,385820.0,616349.508607,12665.022301,198.090662
122,Malta,Europe,441539.0,82.53,4.485,36513.323,1931.0,13.0,188539.0,427004.183096,4373.339614,29.442473
53,Denmark,Europe,5792203.0,80.90,2.500,46682.515,17195.0,626.0,2447911.0,422621.755488,2968.645954,108.076323
96,Israel,Asia,8655541.0,82.97,2.990,33132.320,122539.0,969.0,2353984.0,271962.665303,14157.289533,111.951408
89,Iceland,Europe,341250.0,82.99,2.910,46482.958,2121.0,10.0,88829.0,260304.761905,6215.384615,29.304029
157,Russia,Europe,145934460.0,72.58,8.050,24765.954,1005000.0,17414.0,37176827.0,254750.159763,6886.653091,119.327539
199,United States,North America,331002647.0,78.86,2.770,54225.446,6114406.0,185744.0,83898416.0,253467.507769,18472.377957,561.155633
10,Australia,Oceania,25499881.0,83.44,3.840,44648.710,25923.0,663.0,6255797.0,245326.517406,1016.592979,26.000121

## Create a dataframe with 10 countires that have highest number of positive cases per million people ?

In [21]:
highest_cases_df = combined_df.sort_values('cases_per_million', ascending=False).head(10)

In [22]:
highest_cases_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
155,Qatar,Asia,2881060.0,80.23,1.20,116935.600,119206.0,199.0,634745.0,220316.480740,41375.743650,69.071800
14,Bahrain,Asia,1701583.0,77.29,2.00,43290.705,52440.0,190.0,1118837.0,657527.137965,30818.361490,111.660730
147,Panama,North America,4314768.0,78.51,2.30,22267.037,94084.0,2030.0,336345.0,77952.047480,21805.112117,470.477208
40,Chile,South America,19116209.0,80.18,2.11,22767.037,414739.0,11344.0,2458762.0,128621.841287,21695.671982,593.423100
162,San Marino,Europe,33938.0,84.97,3.80,56861.470,735.0,42.0,NaN,NaN,21657.139490,1237.550828
9,Aruba,North America,106766.0,76.29,NaN,35973.781,2211.0,12.0,NaN,NaN,20708.839893,112.395332
105,Kuwait,Asia,4270563.0,75.49,2.00,65530.537,86478.0,535.0,621616.0,145558.325682,20249.789079,125.276222
150,Peru,South America,32971846.0,76.74,1.60,12236.706,663437.0,29259.0,584232.0,17719.117092,20121.318048,887.393445
27,Brazil,South America,212559409.0,75.88,2.20,14103.452,3997865.0,123780.0,4797948.0,22572.268255,18808.224105,582.331314
199,United States,North America,331002647.0,78.86,2.77,54225.446,6114406.0,185744.0,83898416.0,253467.507769,18472.377957,561.155633

## Create a dataframe with 10 countires that have highest number of deaths cases per million people ?

In [23]:
highest_deaths_df = combined_df.sort_values('deaths_per_million', ascending=False).head(10)

In [24]:
highest_deaths_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
162,San Marino,Europe,33938.0,84.97,3.80,56861.470,735.0,42.0,NaN,NaN,21657.139490,1237.550828
150,Peru,South America,32971846.0,76.74,1.60,12236.706,663437.0,29259.0,584232.0,17719.117092,20121.318048,887.393445
18,Belgium,Europe,11589616.0,81.63,5.64,42658.576,85817.0,9898.0,2281853.0,196887.713967,7404.645676,854.040375
3,Andorra,Europe,77265.0,83.73,NaN,NaN,1199.0,53.0,NaN,NaN,15518.022390,685.950948
177,Spain,Europe,46754783.0,83.56,2.97,34272.360,479554.0,29194.0,6416533.0,137238.001939,10256.790198,624.406705
198,United Kingdom,Europe,67886004.0,81.32,2.54,39753.244,338676.0,41514.0,13447568.0,198090.434075,4988.892850,611.525168
40,Chile,South America,19116209.0,80.18,2.11,22767.037,414739.0,11344.0,2458762.0,128621.841287,21695.671982,593.423100
97,Italy,Europe,60461828.0,83.51,3.18,35220.084,271515.0,35497.0,5214766.0,86248.897403,4490.684602,587.097697
27,Brazil,South America,212559409.0,75.88,2.20,14103.452,3997865.0,123780.0,4797948.0,22572.268255,18808.224105,582.331314
182,Sweden,Europe,10099270.0,82.80,2.22,46949.283,84532.0,5820.0,NaN,NaN,8370.109919,576.279276

In [25]:
highest_tests_df

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
197,United Arab Emirates,Asia,9890400.0,77.97,1.200,67293.483,71540.0,387.0,7177430.0,725696.635121,7233.276713,39.128852
14,Bahrain,Asia,1701583.0,77.29,2.000,43290.705,52440.0,190.0,1118837.0,657527.137965,30818.361490,111.660730
115,Luxembourg,Europe,625976.0,82.25,4.510,94277.965,7928.0,124.0,385820.0,616349.508607,12665.022301,198.090662
122,Malta,Europe,441539.0,82.53,4.485,36513.323,1931.0,13.0,188539.0,427004.183096,4373.339614,29.442473
53,Denmark,Europe,5792203.0,80.90,2.500,46682.515,17195.0,626.0,2447911.0,422621.755488,2968.645954,108.076323
96,Israel,Asia,8655541.0,82.97,2.990,33132.320,122539.0,969.0,2353984.0,271962.665303,14157.289533,111.951408
89,Iceland,Europe,341250.0,82.99,2.910,46482.958,2121.0,10.0,88829.0,260304.761905,6215.384615,29.304029
157,Russia,Europe,145934460.0,72.58,8.050,24765.954,1005000.0,17414.0,37176827.0,254750.159763,6886.653091,119.327539
199,United States,North America,331002647.0,78.86,2.770,54225.446,6114406.0,185744.0,83898416.0,253467.507769,18472.377957,561.155633
10,Australia,Oceania,25499881.0,83.44,3.840,44648.710,25923.0,663.0,6255797.0,245326.517406,1016.592979,26.000121

In [26]:
# using the `isin` method: Checks whether `values` are contained in Series.
highest_tests_df.location.isin(highest_cases_df.location)

197    False
14      True
115    False
122    False
53     False
96     False
89     False
157    False
199     True
10     False
Name: location, dtype: bool

In [27]:
required_count = highest_tests_df.location.isin(highest_cases_df.location).sum()

In [28]:
print(f"The number of countries that feature in both the lists are {required_count}.")

The number of countries that feature in both the lists are 2.

## Count number of countries that feature in both the lists "20 countries with lowest GDP per capita" and "20 countries with the lowest number of hospital beds per thousand population". Only consider countries with a population higher than 10 million while creating the list

In [29]:
lowest_gdp_per_capita = combined_df[combined_df['population'] > 1e7].sort_values('gdp_per_capita').head(20)

In [30]:
lowest_gdp_per_capita

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
32,Burundi,Africa,11890781.0,61.58,0.8,702.225,448.0,1.0,NaN,NaN,37.676247,0.084099
52,Democratic Republic of Congo,Africa,89561404.0,60.68,NaN,808.133,10113.0,258.0,NaN,NaN,112.916944,2.880705
140,Niger,Africa,24206636.0,62.42,0.3,926.000,1177.0,69.0,NaN,NaN,48.623030,2.850458
118,Malawi,Africa,19129955.0,64.26,1.3,1095.042,5579.0,175.0,NaN,NaN,291.636860,9.147957
132,Mozambique,Africa,31255435.0,60.85,0.7,1136.103,4117.0,25.0,NaN,NaN,131.721091,0.799861
117,Madagascar,Africa,27691019.0,67.04,0.2,1416.440,15023.0,196.0,NaN,NaN,542.522469,7.078107
207,Yemen,Asia,29825968.0,66.12,0.7,1479.147,1976.0,571.0,NaN,NaN,66.250993,19.144391
176,South Sudan,Africa,11193729.0,57.85,NaN,1569.888,2532.0,47.0,NaN,NaN,226.198079,4.198780
85,Haiti,North America,11402533.0,64.00,0.7,1653.173,8258.0,206.0,NaN,NaN,724.225047,18.066161
195,Uganda,Africa,45741000.0,63.37,0.5,1697.707,3112.0,32.0,381749.0,8345.882250,68.035242,0.699591
31,Burkina Faso,Africa,20903278.0,61.58,0.4,1703.102,1378.0,55.0,NaN,NaN,65.922675,2.631166
63,Ethiopia,Africa,114963583.0,66.60,0.3,1729.927,54409.0,846.0,869430.0,7562.655732,473.271610,7.358852
39,Chad,Africa,16425859.0,54.24,NaN,1768.153,1017.0,77.0,NaN,NaN,61.914570,4.687730
0,Afghanistan,Asia,38928341.0,64.83,0.5,1803.987,38243.0,1409.0,NaN,NaN,982.394806,36.194710
158,Rwanda,Africa,12952209.0,69.02,NaN,1854.211,4218.0,17.0,393237.0,30360.612618,325.658735,1.312517
209,Zimbabwe,Africa,14862927.0,61.49,1.7,1899.775,6638.0,206.0,97272.0,6544.605918,446.614587,13.859989
82,Guinea,Africa,13132792.0,61.60,0.3,1998.926,9479.0,59.0,NaN,NaN,721.781020,4.492571
121,Mali,Africa,20250834.0,59.31,0.1,2014.306,2802.0,126.0,NaN,NaN,138.364672,6.221966
20,Benin,Africa,12123198.0,61.77,0.5,2064.236,2194.0,40.0,NaN,NaN,180.975350,3.299459
135,Nepal,Asia,29136808.0,70.78,0.3,2442.804,41649.0,251.0,705560.0,24215.418518,1429.429058,8.614533

In [32]:
lowest_hospital_beds = combined_df[combined_df['population'] > 1e7].sort_values('hospital_beds_per_thousand').head(20)

In [33]:
lowest_hospital_beds

,location,continent,population,life_expectancy,hospital_beds_per_thousand,gdp_per_capita,total_cases,total_deaths,total_tests,tests_per_million,cases_per_million,deaths_per_million
121,Mali,Africa,2.025083e+07,59.31,0.10,2014.306,2802.0,126.0,NaN,NaN,138.364672,6.221966
117,Madagascar,Africa,2.769102e+07,67.04,0.20,1416.440,15023.0,196.0,NaN,NaN,542.522469,7.078107
140,Niger,Africa,2.420664e+07,62.42,0.30,926.000,1177.0,69.0,NaN,NaN,48.623030,2.850458
135,Nepal,Asia,2.913681e+07,70.78,0.30,2442.804,41649.0,251.0,705560.0,24215.418518,1429.429058,8.614533
82,Guinea,Africa,1.313279e+07,61.60,0.30,1998.926,9479.0,59.0,NaN,NaN,721.781020,4.492571
63,Ethiopia,Africa,1.149636e+08,66.60,0.30,1729.927,54409.0,846.0,869430.0,7562.655732,473.271610,7.358852
31,Burkina Faso,Africa,2.090328e+07,61.58,0.40,1703.102,1378.0,55.0,NaN,NaN,65.922675,2.631166
195,Uganda,Africa,4.574100e+07,63.37,0.50,1697.707,3112.0,32.0,381749.0,8345.882250,68.035242,0.699591
0,Afghanistan,Asia,3.892834e+07,64.83,0.50,1803.987,38243.0,1409.0,NaN,NaN,982.394806,36.194710
20,Benin,Africa,1.212320e+07,61.77,0.50,2064.236,2194.0,40.0,NaN,NaN,180.975350,3.299459
90,India,Asia,1.380004e+09,69.66,0.53,6426.674,3853406.0,67376.0,44337201.0,32128.304433,2792.314316,48.823033
80,Guatemala,North America,1.791557e+07,74.30,0.60,7423.808,75664.0,2790.0,NaN,NaN,4223.366193,155.730488
145,Pakistan,Asia,2.208923e+08,67.27,0.60,5034.708,297014.0,6328.0,2662508.0,12053.419817,1344.609832,28.647441
85,Haiti,North America,1.140253e+07,64.00,0.70,1653.173,8258.0,206.0,NaN,NaN,724.225047,18.066161
207,Yemen,Asia,2.982597e+07,66.12,0.70,1479.147,1976.0,571.0,NaN,NaN,66.250993,19.144391
187,Tanzania,Africa,5.973421e+07,65.46,0.70,2683.304,509.0,21.0,NaN,NaN,8.521080,0.351557
132,Mozambique,Africa,3.125544e+07,60.85,0.70,1136.103,4117.0,25.0,NaN,NaN,131.721091,0.799861
32,Burundi,Africa,1.189078e+07,61.58,0.80,702.225,448.0,1.0,NaN,NaN,37.676247,0.084099
33,Cambodia,Asia,1.671897e+07,69.82,0.80,3645.070,274.0,0.0,NaN,NaN,16.388568,0.000000
204,Venezuela,South America,2.843594e+07,72.06,0.80,16745.022,48883.0,398.0,NaN,NaN,1719.056759,13.996371

In [34]:
lowest_gdp_per_capita.location.isin(lowest_hospital_beds.location)

32      True
52     False
140     True
118    False
132     True
117     True
207     True
176    False
85      True
195     True
31      True
63      True
39     False
0       True
158    False
209    False
82      True
121     True
20      True
135     True
Name: location, dtype: bool

In [35]:
required_ans = lowest_gdp_per_capita.location.isin(lowest_hospital_beds.location).sum()

In [36]:
print(f"The number of countries that feature in both the lists are {required_ans}.")

The number of countries that feature in both the lists are 14.

In [37]:
combined_df.to_csv('final_results.csv', index=None)